=== goldenforce/nuveen/PropertyMasterPhase2/configuration/Reference/streetreffiles/ConditionalTimeSeries.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT TimeSeriesConfiguration (occurrence)+>
<!ATTLIST TimeSeriesConfiguration
ignoreMappingTSsetting CDATA #IMPLIED>
<!ELEMENT occurrence (option)+>
<!ATTLIST occurrence
table (ft_t_isrt | ft_t_bdst | ft_t_ipdf | ft_t_ppdf | ft_t_isid | ft_t_eqst |
ft_t_ispc | ft_t_bnrt | ft_t_bnmw) #REQUIRED>
<!ELEMENT option (attribute*,where?)>
<!ATTLIST option
MatchingTolerance CDATA "0"
TS_OVERLAP_OVERRIDE (y | Y | n | N) "N"
messageTypes CDATA #IMPLIED
id CDATA #REQUIRED>
<!ELEMENT attribute (#PCDATA)>
<!ELEMENT where (field)+>
<!ELEMENT field EMPTY>
<!ATTLIST field
name CDATA #REQUIRED
value CDATA #REQUIRED
lookup CDATA #IMPLIED
valueOf CDATA #IMPLIED
dataType (STRING | DATE | DATETIME | NUMBER | DECIMAL | TIME) "STRING"
optr CDATA #IMPLIED
multiValue CDATA #IMPLIED
table CDATA #IMPLIED>

=== goldenforce/nuveen/PropertyMasterPhase2/configuration/Reference/streetreffiles/TimeSeries.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TimeSeriesConfiguration SYSTEM "ConditionalTimeSeries.dtd">
<TimeSeriesConfiguration>
	<!-- ************This is Table level Time Series ************ -->
	<occurrence table="ft_t_fiid">
		<option id="FIID_1" messageTypes="WMVF1">
			<attribute>FINS_ID</attribute>
			<where>
				<field name="ft_t_fiid.fins_id_ctxt_typ" value="WMISSRNO,IBEI" multiValue="true" optr="NOT_EQUAL"/>
			</where>
		</option>
	</occurrence>
	<occurrence table="ft_t_irid">
		<option id="IRID_1" messageTypes="WMVF1">
			<attribute>ISSR_ID</attribute>
			<where>
				<field name="FT_T_IRID.ISSR_ID_CTXT_TYP" value="WMISSRNO,IBEI" multiValue="true" optr="NOT_EQUAL"/>
			</where>
		</option>
	</occurrence>
	<occurrence table="ft_t_isid">
		<option id="ISID_1" messageTypes="WMVF1">
			<attribute>ISS_ID</attribute>
		</option>
	</occurrence>
	<occurrence table="ft_t_ppdf">
		<option id="PPDF_1" messageTypes="WMVF1" TS_OVERLAP_OVERRIDE="Y">
		</option>
		<option id="PPDF_2" messageTypes="LRD_Facility" TS_OVERLAP_OVERRIDE="Y">
		 <attribute>EV_CAMT</attribute>	
  		 <attribute>EV_CRTE</attribute>
		</option>
	</occurrence>
	<occurrence table="ft_t_ipdf">
		<option id="IPDF_1" messageTypes="WMVF1" TS_OVERLAP_OVERRIDE="Y">
			<where>
				<field name="fT_T_bdch.cpn_typ" value="FIXED" lookup="BDCH"/>
				<field name="fT_T_bdch.specific_cpn_typ" value="VARIABLE THEN FIXED,VARIABLE THEN FIXED N THEN VARIABLE AGN,FIXED THEN VARIABLE N THEN FIXED AGN" multiValue="true" lookup="BDCH"/>
			</where>
		</option>
		<option id="IPDF_2" messageTypes="WMVF1" TS_OVERLAP_OVERRIDE="Y">
			<where>
				<field name="fT_T_bdch.cpn_typ" value="FIXED" optr="NOT_EQUAL" lookup="BDCH"/>
			</where>
		</option>
		<option id="IPDF_3">
			<where>
				<field name="ft_t_bdch.cpn_typ" value="FLOATING" lookup="BDCH"/>
			</where>
		</option>
		<!-- ************This is Attribute level Time Series ************ -->
		<option id="IPDF_4">
			<attribute>EV_CRTE</attribute>
			<where>
				<field name="fT_T_bdch.cpn_typ" value="VARIABLE" lookup="BDCH"/>
			</where>
		</option>
	</occurrence>
</TimeSeriesConfiguration>
