=== goldenforce/nuveen/PropertyMasterPhase2/configuration/Reference/streetreffiles/SetMatchKey.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT MatchKeyConfiguration (SEGMENT)+>
<!ATTLIST MatchKeyConfiguration
  xmlns CDATA #FIXED ''>

<!ELEMENT SEGMENT (OPTION)+>
<!ATTLIST SEGMENT
  xmlns CDATA #FIXED ''
  name NMTOKEN #REQUIRED>

<!ELEMENT OPTION (CONDITION*,MATCHKEYNAME,ISSUETYPE?,MSGTYPE?,OVERRIDELOOKUPMATCHKEY?)>
<!ATTLIST OPTION
  xmlns CDATA #FIXED ''
  id CDATA #REQUIRED>

<!ELEMENT CONDITION (#PCDATA)>
<!ATTLIST CONDITION
  xmlns CDATA #FIXED ''>

<!ELEMENT MATCHKEYNAME (#PCDATA)>
<!ATTLIST MATCHKEYNAME
  xmlns CDATA #FIXED ''>

<!ELEMENT ISSUETYPE (#PCDATA)>
<!ATTLIST ISSUETYPE
  xmlns CDATA #FIXED ''>

<!ELEMENT MSGTYPE (#PCDATA)>
<!ATTLIST MSGTYPE
  xmlns CDATA #FIXED ''>

<!ELEMENT OVERRIDELOOKUPMATCHKEY (#PCDATA)>
<!ATTLIST OVERRIDELOOKUPMATCHKEY
  xmlns CDATA #FIXED ''>

=== goldenforce/nuveen/PropertyMasterPhase2/configuration/Reference/streetreffiles/SetMatchKey.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MatchKeyConfiguration SYSTEM "SetMatchKey.dtd">
<MatchKeyConfiguration>
	<SEGMENT name="IssueIdentifier">
		<OPTION id="1">
			<CONDITION>ID_CTXT_TYP="BB,BBUNIQUE,BBIDSEC,BBGLOBAL,BBERG,CUSIP,ISIN,CINS,LIN"</CONDITION>
			<MATCHKEYNAME>ISID1_INSTR_ID_CNTXT</MATCHKEYNAME>
			<MSGTYPE>NVNBBPerSecLoans,NVNBBPerSecNonLoans</MSGTYPE>
		</OPTION>
		<!-- Added for Single Listing-->
		<OPTION id="2">
			<CONDITION>ID_CTXT_TYP="BBIDXTKR,BBUNIQUE,BBGLOBAL,BBUNQTCK,BBIDXTKR,BBINDX,SEDOL,INTRNLID,OTHERS,RIC,TRDGSYMB,EXTICKER,OCCCODE,CPTICKER,EQFUNDTK"</CONDITION>
			<MATCHKEYNAME>ISID3_ID_CTXT_ISS_ID</MATCHKEYNAME>
		</OPTION>
		<OPTION id="3">
			<CONDITION>ID_CTXT_TYP="AIICODE,APEXDERINSTRID,AUSTRIA,BB,BBCONNECT,BBCPTICK,BELGIUM,CINS,COMMON,CUSIP,DUTCH,FRENCH,ISIN,LOCAL,PILC,PREISIN,RTASSET,RTTICKER,SICOVAM,SNPCIQINTID,SNPCIQSECID,SNPINSTPROG,SNPINSTR,SNPINSTSYM,SNPRXSEC,SNPSEC,TRDSYMIL,VALOREN"</CONDITION>
			<MATCHKEYNAME>ISID9_INSTR_CTX_USG</MATCHKEYNAME>
		</OPTION>
		<OPTION id="4">
			<CONDITION>IDBBGBSHRCLASSLEVEL,IDCMONUM,MDYDBTNO,MDYDEALNO,SEDOL,TRDGSYSID,WI-TRDGSYSID"</CONDITION>
			<MATCHKEYNAME>ISID_MATCH_1</MATCHKEYNAME>
		</OPTION>
		<OPTION id="5">
			<MATCHKEYNAME>ISID3_ID_CTXT_ISS_ID</MATCHKEYNAME>
		</OPTION>
	</SEGMENT>
	<SEGMENT name="MarketIssueCharacteristics">
		<OPTION id="1">
			<MATCHKEYNAME>MKIS_MATCH_1</MATCHKEYNAME>
		</OPTION>
	</SEGMENT>
	<SEGMENT name="MKISFinsMarketCalendarParticipant">
		<OPTION id="1">
			<MATCHKEYNAME>MKCA_MATCH_2</MATCHKEYNAME>
		</OPTION>
	</SEGMENT>
</SEGMENT>
</MatchKeyConfiguration>
